### ISSUE TITLE
How do we do support and ops?

### ISSUE THREAD

**Issue by danblundell** [lgss/lgss-digital-tech-playbook#41]
Detail support and Ops processes and guidance

**Comment by danblundell** [comment]
#42 PR raised to review the first draft of the support/ops processes and guidance

**Comment by danblundell** [comment]
@SturatParker @Pickett82 @AlanWW @13enedict @AnthonyTaylor comments on the pull request or here welcomed please. 

It's only a first draft but we have to start somewhere right?

**Comment by SteveRBolton** [comment]
Steve Bolton - Notes on support as a project:

1. Current process for Mileage and Expenses calls is different than on diagram, current process is:

Call raised by customer in Let's Go Direct or telephone and go to either the PCT/HR servicedesk (David Guest) team or either the NCC or CCC I.T. Servicedesk (most go through the PCT/HR route).

If call goes through to PCT/HR team they will triage and try to resolve using their knowledge and information they can access, if they are unable to resolve they will reassign to LGSS Digital (currently the NCC-IT-Developers queue).

If call goes through to the I.T. Servicedesk they will assign directly to LGSS Digital (this can be either the NCC-IT-Developers or LGSS-Digital queues, mostly the former).

If there is a technical issue with the system, something needs fixed with the customer account or advice/information/education on the M&E system is needed to be provided this is currently done by the LGSS Digital team.

If there is an issue with the customers job assignment (ie their job has changed), their line manager is incorrect or blank and this has not been updated in the latest establishment report taken from ERPGold or they do not show on the establishment report at all the call is reassigned to the Business Systems team.

2. When call is triaged Operations Lead will add a note which includes the word 'Approved', can the Subject also be added to to include 'Approved' so it is easier for developers to see which calls are support and have been triaged.

**Comment by SteveRBolton** [comment]
> @SteveRBolton
> 
> > 1. When call is triaged Operations Lead will add a note which includes the word 'Approved', can the Subject also be added to to include 'Approved' so it is easier for developers to see which calls are support and have been triaged.
> 
> Absolutely, makes more sense to see if from the dashboard

**Comment by SteveRBolton** [comment]
@danblundell 

Useful to have both the subject added to and a note created then we can see who the Operations Lead is who triaged the call from the name stamp in the notes.

**Comment by SturatParker** [comment]
Something not mentioned is having some kind of knowledge base for support documents. This was super useful on the service desk even though it was just a OneNote in a network folder. It was primitive, but really useful for new and existing staff to refer to. Does this stuff belong in the tech playbook/huddle/sharepoint.lgss.local etc?

Ideally it would have a place to put public documents for users which we could link to since LANDesk is awful at sending documents and letting teams manage the known errors/solutions

**Comment by danblundell** [comment]
@SturatParker exactly right: https://github.com/lgss/lgss-digital-tech-playbook/tree/feature/support/support see 'documentation.md' - although the folder/link isn't actually set up as far as I know.... or a template for that matter, we agree that these are things that need to exist though?

**Comment by AnthonyTaylor** [comment]
I agree we need a repository of knowledge that we can all see and amend.

**Comment by AlanWW** [comment]
What about a "small" feature request, presumably this wouldn't have a project created as it's under X number of days. Perhaps we could have categories e.g. Support - Approved/Rejected. 
Feature Request Minor/Major (X days) - Approved/Rejected

**Comment by SteveRBolton** [comment]
Question for the group. How do you think it best to manage LANDesk calls which are change requests where the customer has to go and get authorisation or find a budget. The ideal would be to set the incident as 'With customer' but this means the incident will auto resolve after 10 days and the customer will likely get annoyed at this and if the incident is the only place where the details of the requested changes have been recorded it get's lost/forgotten when the incident is closed.

My only thought is to set the incident as 'Scheduled activity' with a reasonable period so it allows the customer time to get authority.

This may only be relevant to Firmstep change requests where the changes will take more than one day and the customer has to find a budget but I'd like all comments or ideas so we have a consistent approach.

Thanks

**Comment by SturatParker** [comment]
When a call is resolved in landesk there is a 3 week period where it can be unresolved. After three weeks the status is changed from "Resolved" to "Closed" at which point it is a dead case.

The user is emailed when you send the With Customer, reminded at the halfway mark. Our general philosophy on the service desk was that if they don't respond to us within 2+3 weeks then their case is not important enough to them to be important to us.

However, I did still use Steve's suggestion of scheduled activity for times when I knew a customer would be on annual leave etc. Alternatively there is a tick box on the With Customer page which lets you override the automatic resolution timer. You can't set a new time, and it does still email them the same reminders, but the case doesn't get resolved.

@SteveRBolton what do you consider to be a 'reasonable period'?

**Comment by SteveRBolton** [comment]
At NCC it can be the case that the business takes 4 weeks plus to go through the process of discussing internally, getting authority to spend. It may well be the same at Cambridgeshire.

The 'With customer' option is OK but we would need to have a consistent message to give to the customer on what will happen if they don't respond within the 10 days as once the incident is resolved it dissapears which is the reminder for us to be proactive and chase for an update.

The override on the automatic resolution could be the answer, I didn't know we had that facility bt still think a consient message to the customer advising timescales they should respond one way or another otherwise they will need to raise a new request, manage the customers expectation and politely push the emphasis back to them to get things done their side which is what should happen but sometimes doesn't.

**Comment by danblundell** [comment]
Content is all merged and will evolve - closing original issue.
